# Generated by Django 2.1.15 on 2020-09-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='texto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
